[package]
name = "horror"
version = "0.1.4"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[features]
debug = []

[dependencies]
bevy = { version = "0.11.0", features=["jpeg"] }
bevy-inspector-egui = "0.19.0"
rand = "0.8.5"
bevy_rapier3d = "0.22.0"
bevy_atmosphere = "0.7.0"
