[package]
name = "horror"
version = "0.1.4"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[features]
debug = []

[dependencies]
bevy = { version = "0.11.0", features=["jpeg"] }
bevy_gltf_components = { git="https://github.com/kaosat-dev/Blender_bevy_components_worklflow.git" }
bevy-inspector-egui = "0.19.0"
rand = "0.8.5"
bevy_rapier3d = "0.22.0"
bevy_atmosphere = "0.7.0"
leafwing-input-manager = "0.10.0"
bevy_asset_loader = "0.17.0"
